apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  pipeline: tekton
resources:
- tasks/generate-build-id.yml
- tasks/cleanup-workspace.yml
- tasks/git-clone.yml
- tasks/npm-build.yml
- tasks/npm-install.yml
- tasks/npm-test.yml
- pipelines/npm-test-and-build.yml