apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: npm-multi-stag-pr-
spec:
  resources:
    - name: source-repo
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/cdbkr/nuxt
    - name: settings-repo
      resourceSpec:
        type: git
        params:
          - name: revision
            value: main
          - name: url
            value: https://github.com/kairen/acs-webhook
  podTemplate:
    securityContext:
      runAsUser: 1001 # 0 will be success
  pipelineRef:
    name: npm-test-and-build
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2-csi