apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kaniko-build-push-private
spec:
  serviceAccountName: pipeline
  resources:
    inputs:
    - name: source-repo
      resourceSpec:
        type: git
        params:
          - name: revision
            value: main
          - name: url
            value: https://github.com/kairen/docker-build-push.git
  taskRef:
    name: kaniko-build-push