apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dind-build
spec:
  steps:
  - image: docker.io/library/docker:stable
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2376
    - name: DOCKER_TLS_VERIFY
      value: '1'
    - name: DOCKER_CERT_PATH
      value: /certs/client
    name: client
    script: |
      #!/usr/bin/env sh
      
      cat > .dockerignore <<EOF
      *
      EOF

      # Write a Dockerfile and `docker build` it.
      cat > Dockerfile << EOF
      FROM ubuntu:20.04
      RUN apt-get update
      ENTRYPOINT ["echo", "Hello Docker in Docker!!"]
      EOF
      
      docker build -t hello .
      docker images

      # ...then run it!
      docker run hello
      
    volumeMounts:
      - mountPath: /certs/client
        name: dind-certs
  sidecars:
    - image: docker.io/library/docker:dind
      name: server
      args:
        - --storage-driver=vfs
        - --userland-proxy=false
        - --debug
      securityContext:
        privileged: true
      env:
      - name: DOCKER_TLS_CERTDIR
        value: /certs
      volumeMounts:
      - mountPath: /certs/client
        name: dind-certs
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ['ls', '/certs/client/ca.pem']
  volumes:
  - name: dind-certs
    emptyDir: {}