apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: dind-build-push-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
  - ref:
      name: github
    params:
      - name: secretRef
        value:
          secretName: github-webhook-secret
          secretKey: secretToken
      - name: eventTypes
        value: ["push"]
  bindings:
    - ref: dind-build-push
  template:
    ref: dind-build-push
